#! /bin/csh -f
#
# Scriptfile
#
# rho    = density
# lmax   = number of steps
# nequil = number of equilibration steps
# dr     = maximum displacement
# npart  = number of particles

foreach rho (0.70)

cat > fort.15  <<endofdata
  ibeg  nequil   lmax  nsamp  
     0     100   5000      1        
    dr
  0.09 
ndispl
    50  
 npart    temp    rho
   100     2.0  ${rho} 
endofdata

cp lj.res      fort.11
cp lj.model    fort.25

time  ../Source/mc_nvt  > out 

mv fort.21     lj.res
mv fort.22     movie.pdb
mv fort.66     lj.energy
mv fort.67     lj.pressure
rm fort.*

end
exit
