      Double Precision Eps4,Sig2,Mass,Rc2,Eps48,Rc

      Common /Pot1/ Eps4,Eps48,Sig2,Mass,Rc(2),Rc2(2)
C
C     Eps4      : 4 * Epsilon 
C     Eps48     : 48 * Epsilon
C     (Epsilon) : Energy Parameter Lennard-Jones Potential
C     Sig2      : Sigma*Sigma
C     (Sigma)   : Size Parameter Lennard-Jones Potenital
C     Mass      : Mass Of The Molecules
C     Rc        : Cut-Off Radius Of The Potenial
C     Rc2       : Rc * Rc
