#! /bin/csh -f
#
# temp   = temperature
# lmax   = total number of steps
# nequil = number of init. steps
# npart  = number of particles
# rho    = density of each box

set temp = 0.8d0 

cat > fort.15  <<endofdata
ibeg  nequil  lmax  nsamp  
   0     100  3000      1  
  dr    vmax  succ
0.09    0.01   50.
ndispl  nvol nswap
  200      2    20
npart   temp   rho 
256  ${temp}   .31
rv
3.0 
endofdata

cp lj.res               fort.11
cp lj.model             fort.25

time ../Source/Gibbs > out

cp fort.21              lj.res
mv fort.66              lj.prt
mv fort.45              lj.densplot
rm fort.*

exit
