#! /bin/csh -f
#
# NSTEP     = NUMBER OF TIMESTEPS
# NINIT     = NUMBER OF INITIALIZATION STEPS
# TEMP      = TEMPERATURE
# NCHOI     = NUMBER OF TRIAL POSITIONS
# NUALL     = CHAIN LENGTH
# LSTATIC   = STATIC SCHEME ?
# LCBMC     = DO WE USE CBMC ?
# RCUT      = POTENTIAL CUT-OFF
# A         = PREFACTOR NONBONDED POTENTIAL
# KB        = BOND-BENDING CONSTANT
# THETAN    = EQUILIBRIUM ANGLE [RADIALS]

set NSTEP     = 100
set NINIT     = 5
set TEMP      = 2.0d0
set NCHOI     = 5
set LSTATIC   = .true.
set LCBMC     = .true.
set NUALL     = 10
set RCUT      = 1.0D0
set A         = 2.0D0
set KB        = 10.0D0
set THETAN    = 2.0D0

cat > fort.21 <<endofdata
$NSTEP   $NINIT $NUALL    $NCHOI
$LSTATIC $LCBMC
$TEMP    $RCUT  $A        $KB      $THETAN
endofdata

time ../Source/polymer > out

mv fort.22 system.pdb
mv fort.23 distri
rm fort.*

exit
