#! /bin/csh -f
#
# BOX      = BOXLENGTH
# NPART    = NUMBER OF PARTICLES
# NSTEP    = NUMBER OF TIMESTEPS
# NINIT    = NUMBER OF INITIALIZATION STEPS
# TEMP     = TEMPERATURE
# TSTEP    = TIMESTEP FOR INTEGRATION

set BOX    = 5.0
set NPART  = 100
set NSTEP  = 5000
set NINIT  = 500
set TEMP   = 1.5
set TSTEP  = 0.0005

cat > fort.21 <<endofdata
$BOX    $NPART $NSTEP  $TEMP  $TSTEP $NINIT
endofdata

time ../Source/md_nve > out

mv fort.22 system.pdb 
mv fort.23 lj.gyra
mv fort.24 lj.vacf
mv fort.25 lj.msd    
rm fort.*

exit
