########################################
##
## written by W. Shinoda
##

## 7) for Intel ver9.0 for windows
FC     = ifort
CC     = gcc
#FFLAGS = -w -QaxB -Qftz -O3 -QxB -Qfpp -DPCC -DPUBFFT
FFLAGS = -fpp -Qpad /DPCC /DPUBFFT /DCUBIC /DSURF 
LFLAGS = -fpp -Qpad /DPCC /DPUBFFT /DCUBIC /DSURF
PFLAGS = -fpp -Qpad /DPCC /DPUBFFT /DCUBIC /DSURF
#SFLAGA = -lmkl_lapack -lmkl_itp -lguide -pthread
#PFLAGA = -lmkl_lapack -lmkl_itp
PFC    = ifort

include make.win.mpdyn

#< end of Makefile>
